version: '3.1'

services:

  db:
    container_name: db_container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: asistencia
    ports:
      - 3308:3306
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  java-app:
    build:
      context: .
    container_name: java-console-app
    image: java-console-app:latest
    stdin_open: true 
    tty: true
