version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: asistencia
    ports:
      - 3308:3306
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql